version: 2.1

orbs:
  slack: circleci/slack@4.4.4

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  slack-test:
    docker:
      - image: 'cimg/base:stable'    
    steps:
      - checkout
      - run:
          name: "Say hi"
          command: "echo Hello, World!"
      - notify_slack_error
      - notify_slack_pass     

workflows:
  deploy-test:
    jobs:
      - slack-test:
          context: slack-secrets
      